version: 2

sources:
  - name: corentin       # Logical name for your source (you can choose this)
    tables:
      - name: stateprovince   # The actual table name in your database
        description: "State and province data from eve' schema"
      - name: product   # The actual table name in your database
        description: "State and province data from eve' schema"
      - name: productcategory   # The actual table name in your database
        description: "State and province data from eve' schema"

      - name : customer
      
      - name : date
        description : "dates in an intervall of few years"

      - name : salesorderdetail
        description : 'details of the commands'

      - name : salesorderheader
        description : 'main informations of the commands'
      
      - name : store1 
<<<<<<< HEAD
        description : 'informations about the stores' 
=======
        description : informations about the stores 
>>>>>>> origin/corentin

      - name : productsubcategory


<<<<<<< HEAD
      - name : person

      - name : address

=======
>>>>>>> origin/corentin
      